/**
 * Vault Architect - Deterministic Password Generator
 * 
 * A secure, deterministic password generator that creates consistent passwords
 * across devices using the same inputs (master password + site name + parameters).
 * 
 * Algorithm: PBKDF2-HMAC-SHA256
 * License: GPLv3
 */

const crypto = require('crypto');

// Default configuration
const DEFAULT_ITERATIONS = 100000;
const DEFAULT_SALT_LENGTH = 16;
const DEFAULT_OUTPUT_LENGTH = 8;
const DEFAULT_SPECIAL_CHARS = '@#^!?';
const DEFAULT_BLACKLIST = [' ']; // Default blacklist to filter customSymbols

/**
 * Blacklist for common weak passwords/patterns
 */
const COMMON_BLACKLIST = [
    'password', '123456', '12345678', 'qwerty', 'abc123',
    'monkey', 'master', 'dragon', '111111', 'baseball',
    'iloveyou', 'trustno1', 'sunshine', 'princess', 'admin'
];

/**
 * Generate a deterministic password from master password and site name
 * 
 * Password requirements:
 * - At least 1 uppercase letter
 * - At least 1 lowercase letter
 * - At least 1 digit
 * - At least 1 special character (default: @#^!?)
 * - Characters are generated by round-robin mapping to 4 datasets:
 *   [uppercase, lowercase, digits, special symbols]
 * - Characters in blacklist are filtered out from customSymbols and default symbols
 * - Blacklist has higher priority than DEFAULT_SPECIAL_CHARS
 * 
 * @param {Object} options - Generation parameters
 * @param {string} options.masterPassword - Master password (token)
 * @param {string} options.salt - Salt value
 * @param {string} options.customSymbols - Custom symbol set (optional, default: @#^!?)
 * @param {number} options.length - Output password length (default: 8)
 * @param {number} options.iterations - PBKDF2 iterations (default: 100000)
 * @param {Array<string>} options.blacklist - Disallowed characters/patterns (optional)
 * @returns {Promise<string>} Generated password
 */
async function generatePassword(options = {}) {
    const {
        masterPassword,
        salt,
        length = DEFAULT_OUTPUT_LENGTH,
        iterations = DEFAULT_ITERATIONS,
        customSymbols,
        blacklist = DEFAULT_BLACKLIST
    } = options;

    // Validate required parameters
    if (!masterPassword || !salt) {
        throw new Error('masterPassword and salt are required');
    }

    if (length < 8 || length > 128) {
        throw new Error('Password length must be between 8 and 128');
    }

    // Merge blacklist with default blacklist
    const fullBlacklist = [...DEFAULT_BLACKLIST, ...blacklist];

    // Build 4 separate character sets
    const uppercase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const lowercase = 'abcdefghijklmnopqrstuvwxyz';
    const digits = '0123456789';

    // Merge customSymbols with DEFAULT_SPECIAL_CHARS and remove duplicates
    const mergedSymbols = mergeAndDeduplicate(customSymbols, DEFAULT_SPECIAL_CHARS);

    // Filter symbols based on blacklist (blacklist has higher priority)
    const symbols = filterBlacklist(mergedSymbols, fullBlacklist);

    if (symbols.length < 1) {
        throw new Error('After filtering blacklist, there are no special characters available. Please adjust customSymbols.');
    }

    // Build full charset for positions that don't map to specific datasets
    const fullCharset = uppercase + lowercase + digits + symbols;

    // Derive key using PBKDF2
    const derivedKey = crypto.pbkdf2Sync(
        masterPassword,
        salt,
        iterations,
        length * 2, // Generate enough bytes for conversion
        'sha256'
    );

    // Convert derived key to password using dynamic position mapping
    let password = '';
    let keyBuffer = derivedKey;
    let bufferIndex = 0;

    // Use first character to determine which 4 positions map to which dataset
    // This makes the position mapping unpredictable
    const firstCharValue = keyBuffer[0];

    // Generate 4 unique positions in range [0, length-1]
    const selectedPositions = [];
    const availablePositions = Array.from({ length }, (_, i) => i);

    // Select 4 unique positions using firstCharValue
    for (let i = 0; i < 4; i++) {
        const idx = (firstCharValue + i * 7) % availablePositions.length;
        selectedPositions.push(availablePositions[idx]);
        availablePositions.splice(idx, 1);
    }

    // Map datasets to selected positions
    const positionMapping = {
        [selectedPositions[0]]: uppercase,
        [selectedPositions[1]]: lowercase,
        [selectedPositions[2]]: digits,
        [selectedPositions[3]]: symbols
    };

    bufferIndex = 1; // Start from index 1 since index 0 was used for position calculation

    for (let i = 0; i < length; i++) {
        let char = '';

        if (selectedPositions.includes(i)) {
            // This position is one of the 4 mapped positions
            const dataset = positionMapping[i];
            const charIndex = keyBuffer[bufferIndex % keyBuffer.length] % dataset.length;
            char = dataset[charIndex];
        } else {
            // Other positions: use full charset for maximum entropy
            const charIndex = keyBuffer[bufferIndex % keyBuffer.length] % fullCharset.length;
            char = fullCharset[charIndex];
        }

        password += char;
        bufferIndex++;
    }

    return password;
}

/**
 * Merge two strings and remove duplicate characters
 * @param {string} customSymbols - User-provided symbols (can be empty)
 * @param {string} defaultSymbols - Default symbols
 * @returns {string} Merged and deduplicated symbols
 */
function mergeAndDeduplicate(customSymbols, defaultSymbols) {
    // If customSymbols is empty or undefined, return default
    if (!customSymbols) {
        return defaultSymbols;
    }

    // Merge both and remove duplicates
    const combined = customSymbols + defaultSymbols;
    const uniqueChars = [...new Set(combined.split(''))];
    return uniqueChars.join('');
}

/**
 * Filter blacklisted characters from a string
 * @param {string} str - String to filter
 * @param {Array<string>} blacklist - List of characters/patterns to filter
 * @returns {string} Filtered string
 */
function filterBlacklist(str, blacklist) {
    return str.split('').filter(char => {
        return !blacklist.some(pattern => {
            if (typeof pattern === 'string') {
                return char === pattern;
            }
            if (pattern instanceof RegExp) {
                return pattern.test(char);
            }
            return false;
        });
    }).join('');
}

/**
 * Check if password contains blacklisted patterns (for word-based blacklist, not character-based)
 */
function isInBlacklist(password, blacklist) {
    const lowerPassword = password.toLowerCase();
    return blacklist.some(pattern => {
        if (typeof pattern === 'string') {
            // Only check for multi-character patterns or words
            // Single characters are filtered during character set building
            if (pattern.length > 1) {
                return lowerPassword.includes(pattern.toLowerCase());
            }
            return false;
        }
        if (pattern instanceof RegExp) {
            return pattern.test(password);
        }
        return false;
    });
}

/**
 * Ensure password meets character type criteria (deterministic):
 * - At least 1 uppercase letter
 * - At least 1 lowercase letter
 * - At least 1 digit
 * - At least 1 special character
 */
function ensureCriteria(password, keyBuffer, uppercase, lowercase, digits, symbols) {
    let hasUppercase = /[A-Z]/.test(password);
    let hasLowercase = /[a-z]/.test(password);
    let hasDigit = /[0-9]/.test(password);

    // Count characters by type
    const symbolPattern = new RegExp(`[${escapeRegex(symbols)}]`, 'g');
    let actualSymbolCount = (password.match(symbolPattern) || []).length;

    // Replace characters to meet criteria deterministically
    let result = password.split('');
    let indices = Array.from({ length: result.length }, (_, i) => i);

    // Deterministic shuffle using keyBuffer
    for (let i = indices.length - 1; i > 0; i--) {
        const j = keyBuffer[i] % (i + 1);
        [indices[i], indices[j]] = [indices[j], indices[i]];
    }

    let usedIndices = new Set();
    let bufferIndex = 0;

    // Helper function to get next deterministic random value
    const getNextRandom = (max) => {
        const value = keyBuffer[bufferIndex % keyBuffer.length];
        bufferIndex++;
        return value % max;
    };

    // Ensure at least 1 uppercase
    if (!hasUppercase) {
        for (const idx of indices) {
            if (!usedIndices.has(idx)) {
                result[idx] = uppercase[getNextRandom(uppercase.length)];
                usedIndices.add(idx);
                hasUppercase = true;
                break;
            }
        }
    }

    // Ensure at least 1 lowercase
    if (!hasLowercase) {
        for (const idx of indices) {
            if (!usedIndices.has(idx)) {
                result[idx] = lowercase[getNextRandom(lowercase.length)];
                usedIndices.add(idx);
                hasLowercase = true;
                break;
            }
        }
    }

    // Ensure at least 1 digit
    if (!hasDigit) {
        for (const idx of indices) {
            if (!usedIndices.has(idx)) {
                result[idx] = digits[getNextRandom(digits.length)];
                usedIndices.add(idx);
                hasDigit = true;
                break;
            }
        }
    }

    // Ensure at least 1 symbol
    actualSymbolCount = (result.join('').match(symbolPattern) || []).length;
    if (actualSymbolCount < 1) {
        for (const idx of indices) {
            if (!usedIndices.has(idx)) {
                result[idx] = symbols[getNextRandom(symbols.length)];
                usedIndices.add(idx);
                actualSymbolCount = (result.join('').match(symbolPattern) || []).length;
                if (actualSymbolCount >= 1) {
                    break;
                }
            }
        }
    }

    return result.join('');
}

/**
 * Escape special regex characters
 */
function escapeRegex(string) {
    return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Generate multiple passwords in batch
 */
async function generateBatchPasswords(options, siteNames) {
    const results = [];

    for (const siteName of siteNames) {
        const password = await generatePassword({
            ...options,
            siteName
        });
        results.push({ siteName, password });
    }

    return results;
}

/**
 * Validate password strength
 */
function validatePassword(password) {
    const checks = {
        length: password.length >= 8,
        hasLower: /[a-z]/.test(password),
        hasUpper: /[A-Z]/.test(password),
        hasNumber: /[0-9]/.test(password),
        hasSpecial: /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/.test(password),
        notCommon: !COMMON_BLACKLIST.includes(password.toLowerCase())
    };

    const strength = Object.values(checks).filter(Boolean).length;
    let level = 'Weak';
    if (strength >= 5) level = 'Strong';
    else if (strength >= 4) level = 'Medium';

    return {
        ...checks,
        strength,
        level
    };
}

// Export functions
module.exports = {
    generatePassword,
    generateBatchPasswords,
    validatePassword,
    DEFAULT_ITERATIONS,
    DEFAULT_OUTPUT_LENGTH,
    DEFAULT_SPECIAL_CHARS,
    DEFAULT_BLACKLIST,
    ensureCriteria,
    escapeRegex,
    mergeAndDeduplicate,
    filterBlacklist
};
